%% Disruption Analysis 

% import experimental data as "rawdata" (exp01 S/D)

data = rawdata;
maxrich = max(data.RICH);
disr_perc_array = zeros(1,maxrich);
thres = 0.2;

% Supply analysis
%{
results = NaN(6,maxrich);

for j = [3 6 9 12 15 18]

    MaxExt = zeros(maxrich,2);
    data = rawdata(rawdata.SK == j,:);

    for i = 1:maxrich
        rich_data = data(data.RICH == i,:);
        [MaxExt(i,:),disr_perc] = DisruptAnalysis(rich_data,thres);
        disr_perc_array(i) = disr_perc;
    end

    SigExt = MaxExt(:,1);
    SigExt(MaxExt(:,2) < 200) = [];
    disp(MaxExt(:,2))
    disr_perc_array(MaxExt(:,2) < 200) = [];
    results(j/3,1:length(SigExt)) = SigExt;
end

SKPlot(results)
%}


% Diversity analysis

results = NaN(10,maxrich);

for j = [1 2 3 5 7 10]

    MaxExt = zeros(maxrich,2);
    data = rawdata(rawdata.ENV == j,:);

    for i = 1:maxrich
        rich_data = data(data.RICH == i,:);
        [MaxExt(i,:),disr_perc] = DisruptAnalysis(rich_data,thres);
        disr_perc_array(i) = disr_perc;
    end

    SigExt = MaxExt(:,1);
    SigExt(MaxExt(:,2) < 200) = [];
    disr_perc_array(MaxExt(:,2) < 200) = [];
    results(j,1:length(SigExt)) = SigExt;
end

ENVPlot(results)
%}


hold on

% Predicted number of low-rank disruptions given observed disruption percentage
predicted = ceil((1:17)/(1/thres))./(1:17);
predicted = predicted(1:length(disr_perc_array)) .* disr_perc_array;
plot(predicted,'--','DisplayName','Predicted','LineWidth',1,'Color','k')



function [x,disr_perc] = DisruptAnalysis(data,thres) % Change outcome from disrupt to resist if displaced species fall below rank threshold
    
    disr_data = data(data.OUTCOME == 'DISR',:);
    disr_perc = length(disr_data.COM)/length(data.COM);
    EXTRANK = zeros(1,length(disr_data.COM));
    for i = 1:length(disr_data.COM)
        EXTRANK(i) = min(cell2mat(disr_data(i,:).EXTRANK));
    end

    MaxExt = ( disr_data.RICH - EXTRANK.' )./ disr_data.RICH;
    
    % Percent of invasions which result only in extinction of bottom (thres)% species
    
    x = (sum(MaxExt < thres)/length(data.COM)).';
    x(:,2) = length(data.COM);
    %}

    % Percent of disruptions which result only in extinction of bottom (thres)% species
    %{
    x = (sum(MaxExt <= thres)/length(disr_data.COM)).';
    x(:,2) = length(disr_data.COM);
    %}

end

function SKPlot(data)

    %CREATEFIGURE(Y1, Y2, Y3, YMatrix1, Y4)
    %  Y1:  vector of plot y data
    %  Y2:  vector of plot y data
    %  Y3:  vector of plot y data
    %  YMATRIX1:  matrix of plot y data
    %  Y4:  vector of plot y data

    %  Auto-generated by MATLAB on 06-Feb-2025 18:42:31

    % Create figure
    figure;

    % Create axes
    axes1 = axes;
    hold(axes1,'on');

    Y1 = data(1,:);
    Y2 = data(2,:);
    Y3 = data(3,:);
    Y4 = data(4,:);
    Y5 = data(5,:);
    Y6 = data(6,:);

    % Create plot
    plot(Y1,'DisplayName','3','LineWidth',4,'Color',[0.96078431372549 0.87843137254902 0.901960784313726]);
    plot(Y2,'DisplayName','6','LineWidth',4,'Color',[0.941176470588235 0.729411764705882 0.768627450980392]);
    plot(Y3,'DisplayName','9','LineWidth',4,'Color',[0.92156862745098 0.568627450980392 0.63921568627451]);
    plot(Y4,'DisplayName','12','LineWidth',4,'Color',[0.92156862745098 0.388235294117647 0.47843137254902]);
    plot(Y5,'DisplayName','15','LineWidth',4,'Color',[0.901960784313726 0.188235294117647 0.32156862745098]);
    plot(Y6,'DisplayName','18','LineWidth',4,'Color',[0.63921568627451 0.0784313725490196 0.180392156862745]);
    
    % Create ylabel
    ylabel({'Low-Rank Disruption'},'FontSize',24,'FontName','EB Garamond');

    % Create xlabel
    xlabel({'Initial Community Richness'},'FontSize',24,...
        'FontName','EB Garamond');

    % Create title
    title({'Low-Rank Disruption by Richness'},'FontSize',30,...
        'FontName','EB Garamond');

    xlim(axes1,[1 17]);
    ylim(axes1,[0 0.65]);

    hold(axes1,'off');
    
    set(axes1,'FontSize',20,'TickLabelInterpreter','latex','XTick',...
        [1 3 5 7 9 11 13 15 17],'XTickLabel',...
        {'1','3','5','7','9','11','13','15','17'},'YTick',[0 0.2 0.4 0.6 0.8 1], ...
        'YTickLabel',{'0\%','20\%','40\%','60\%','80\%','100\%'});
   
    legend1 = legend(axes1,'show');
    set(legend1,'Interpreter','latex','FontSize',14);
    title(legend1,'Supply');

end

function ENVPlot(data)

    %CREATEFIGURE(Y1, Y2, Y3, YMatrix1, Y4)
    %  Y1:  vector of plot y data
    %  Y2:  vector of plot y data
    %  Y3:  vector of plot y data
    %  YMATRIX1:  matrix of plot y data
    %  Y4:  vector of plot y data

    %  Auto-generated by MATLAB on 06-Feb-2025 18:42:31

    % Create figure
    figure;

    % Create axes
    axes1 = axes;
    hold(axes1,'on');

    Y1 = data(1,:);
    Y2 = data(2,:);
    Y3 = data(3,:);
    Y4 = data(5,:);
    Y5 = data(7,:);
    Y6 = data(10,:);

    % Create plot
    plot(Y1,'DisplayName','1','LineWidth',4,'Color',[0.30,0.75,0.93]);
    plot(Y2,'DisplayName','2','LineWidth',4,'Color',[0 0.529411764705882 0.890196078431372]);
    plot(Y3,'DisplayName','3','LineWidth',4,'Color',[0 0.458823529411765 0.768627450980392]);
    plot(Y4,'DisplayName','5','LineWidth',4,'Color',[0 0.4 0.670588235294118]);
    plot(Y5,'DisplayName','7','LineWidth',4,'Color',[0 0.341176470588235 0.56078431372549]);
    plot(Y6,'DisplayName','10','LineWidth',4,'Color',[0 0.258823529411765 0.431372549019608]);
    
    % Create ylabel
    ylabel({'Low-Rank Disruption'},'FontSize',24,'FontName','EB Garamond');

    % Create xlabel
    xlabel({'Initial Community Richness'},'FontSize',24,...
        'FontName','EB Garamond');

    % Create title
    title({'Low-Rank Disruption by Richness'},'FontSize',30,...
        'FontName','EB Garamond');

    xlim(axes1,[1 13]);
    ylim(axes1,[0 0.65]);

    hold(axes1,'off');
    
    set(axes1,'FontSize',20,'TickLabelInterpreter','latex','XTick',...
        [1 3 5 7 9 11 13 15 17],'XTickLabel',...
        {'1','3','5','7','9','11','13','15','17'},'YTick',[0 0.2 0.4 0.6 0.8 1], ...
        'YTickLabel',{'0\%','20\%','40\%','60\%','80\%','100\%'});
   
    legend1 = legend(axes1,'show');
    set(legend1,'Interpreter','latex','FontSize',14);
    title(legend1,'Diversity');

end