%% Analysis: Richness

% import experimental data as "rawdata" (exp01)

% refine data with parameter ranges
%data = rawdata;
%data = rawdata(rawdata.ENV == 2,:);
%data = data(1:100000,:);
%data = data(data.l == 0.8,:);
%data = data(data.SK >= 6,:);
%data = rawdata;

%DisrFix(data,0.05);


res_total = struct();


for i = [1 2 3 5 7 10]

    data = rawdata(rawdata.ENV == i,:);

    env_data = RichnessAnalysis(data);
    res_total.('E'+string(i)) = env_data.RES(env_data.N >= 100);

end

EnvPlot(res_total)


ylim([0 1])


function summary_data = RichnessAnalysis(data)

    rich_sort = struct();
    summary_data = table('Size',[max(data.RICH)-min(data.RICH)+1 7], ...
        'VariableTypes',{'double','double','double','double','double','double','double'},...
        'VariableNames',{'N',     'LOAD',  'ENV',   'S',     'LOADf', 'RICHf', 'RES'});


    for i = min(data.RICH):max(data.RICH)
        rich_sort.('R'+string(i)) = data(data.RICH == i,:);

        summary_data(i-min(data.RICH)+1,:) = {length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).LOAD)/length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).ENV)/length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).S)/length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).LOADf)/length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).RICHf)/length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).OUTCOME == 'RES') / length(rich_sort.('R'+string(i)).COM)};
    end
end

function DisrFix(data,thres) % Change outcome from disrupt to resist if displaced species fall below rank threshold
    
    for i = 1:length(data.COM)
        EXTRANK = cell2mat(data(i,:).EXTRANK);
        if sum(EXTRANK) ~= 0 && sum(1-(EXTRANK / data(i,:).RICH) > thres) == 0
            data(i,:).OUTCOME = 'RES';
            disp(data(i,:).COM)
        end
    end

end

function EnvPlot(data_struct)

    %CREATEFIGURE(Y1, Y2, Y3, YMatrix1, Y4)
    %  Y1:  vector of plot y data
    %  Y2:  vector of plot y data
    %  Y3:  vector of plot y data
    %  YMATRIX1:  matrix of plot y data
    %  Y4:  vector of plot y data

    %  Auto-generated by MATLAB on 06-Feb-2025 18:42:31

    % Create figure
    figure;

    % Create axes
    axes1 = axes;
    hold(axes1,'on');

    Y1 = data_struct.E1;
    Y2 = data_struct.E2;
    Y3 = data_struct.E3;
    Y4 = data_struct.E5;
    Y5 = data_struct.E7;
    Y6 = data_struct.E10;

    % Create plot
    plot(Y1,'DisplayName','1','LineWidth',3,'Color',[0.30,0.75,0.93],'Marker','.','MarkerSize',30);
    plot(Y2,'DisplayName','2','LineWidth',3,'Color',[0 0.529411764705882 0.890196078431372],'Marker','.','MarkerSize',30);
    plot(Y3,'DisplayName','3','LineWidth',3,'Color',[0 0.458823529411765 0.768627450980392],'Marker','.','MarkerSize',30);
    plot(Y4,'DisplayName','5','LineWidth',3,'Color',[0 0.4 0.670588235294118],'Marker','.','MarkerSize',30);
    plot(Y5,'DisplayName','7','LineWidth',3,'Color',[0 0.341176470588235 0.56078431372549],'Marker','.','MarkerSize',30);
    plot(Y6,'DisplayName','10','LineWidth',3,'Color',[0 0.258823529411765 0.431372549019608],'Marker','.','MarkerSize',30);
    
    % Create ylabel
    ylabel({'Resistance Outcomes'},'FontSize',24,'FontName','EB Garamond');

    % Create xlabel
    xlabel({'Initial Community Richness'},'FontSize',24,...
        'FontName','EB Garamond');

    % Create title
    % title({'Richness-Resistance Curve','by Resource Diversity'},'FontSize',30,...
    %    'FontName','EB Garamond');

    xlim(axes1,[1 17]);
    ylim(axes1,[0 1]);

    hold(axes1,'off');
    
    set(axes1,'FontSize',20,'TickLabelInterpreter','latex','XTick',...
        [1 3 5 7 9 11 13 15 17],'XTickLabel',...
        {'1','3','5','7','9','11','13','15','17'},'YTickLabel',...
        {'0\%','20\%','40\%','60\%','80\%','100\%'});
   
    legend1 = legend(axes1,'show');
    set(legend1,'Interpreter','latex','FontSize',14);
    title(legend1,'Diversity');
end