%% Analysis: Richness-Resistance by Resource Supply (Figure 3b)

% import experimental data as "rawdata" (exp01)

data = rawdata;
res_total = struct();

for i = [3 6 9 12 15 18]
    data = rawdata(rawdata.SK == i,:);
    sk_data = RichnessAnalysis(data);
    res_total.('K'+string(i)) = sk_data.RES(sk_data.N >= 100); % minimum sample size
end

SKPlot(res_total)
ylim([0 1])

function summary_data = RichnessAnalysis(data)

    rich_sort = struct();
    summary_data = table('Size',[max(data.RICH)-min(data.RICH)+1 7], ...
        'VariableTypes',{'double','double','double','double','double','double','double'},...
        'VariableNames',{'N',     'LOAD',  'ENV',   'S',     'LOADf', 'RICHf', 'RES'});


    for i = min(data.RICH):max(data.RICH)
        rich_sort.('R'+string(i)) = data(data.RICH == i,:);

        summary_data(i-min(data.RICH)+1,:) = {length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).LOAD)/length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).ENV)/length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).S)/length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).LOADf)/length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).RICHf)/length(rich_sort.('R'+string(i)).COM),...
            sum(rich_sort.('R'+string(i)).OUTCOME == 'RES') / length(rich_sort.('R'+string(i)).COM)};
    end
end

function SKPlot(data_struct)

    %CREATEFIGURE(Y1, Y2, Y3, YMatrix1, Y4)
    %  Y1:  vector of plot y data
    %  Y2:  vector of plot y data
    %  Y3:  vector of plot y data
    %  YMATRIX1:  matrix of plot y data
    %  Y4:  vector of plot y data

    %  Auto-generated by MATLAB on 06-Feb-2025 18:42:31

    % Create figure
    figure;

    % Create axes
    axes1 = axes;
    hold(axes1,'on');

    Y1 = data_struct.K3;
    Y2 = data_struct.K6;
    Y3 = data_struct.K9;
    Y4 = data_struct.K12;
    Y5 = data_struct.K15;
    Y6 = data_struct.K18;

    % Create plot
    plot(Y1,'DisplayName','3','LineWidth',4,'Color',[0.96078431372549 0.87843137254902 0.901960784313726],'Marker','.','MarkerSize',30);
    plot(Y2,'DisplayName','6','LineWidth',4,'Color',[0.941176470588235 0.729411764705882 0.768627450980392],'Marker','.','MarkerSize',30);
    plot(Y3,'DisplayName','9','LineWidth',4,'Color',[0.92156862745098 0.568627450980392 0.63921568627451],'Marker','.','MarkerSize',30);
    plot(Y4,'DisplayName','12','LineWidth',4,'Color',[0.92156862745098 0.388235294117647 0.47843137254902],'Marker','.','MarkerSize',30);
    plot(Y5,'DisplayName','15','LineWidth',4,'Color',[0.901960784313726 0.188235294117647 0.32156862745098],'Marker','.','MarkerSize',30);
    plot(Y6,'DisplayName','18','LineWidth',4,'Color',[0.63921568627451 0.0784313725490196 0.180392156862745],'Marker','.','MarkerSize',30);
    
    % Create ylabel
    ylabel({'Resistance Outcomes'},'FontSize',24,'FontName','EB Garamond');

    % Create xlabel
    xlabel({'Initial Community Richness'},'FontSize',24,...
        'FontName','EB Garamond');

    % Create title
    %title({'Richness-Resistance Curve','by Resource Supply'},'FontSize',30,...
    %    'FontName','EB Garamond');

    xlim(axes1,[1 17]);
    ylim(axes1,[0 1]);

    hold(axes1,'off');
    
    set(axes1,'FontSize',20,'TickLabelInterpreter','latex','XTick',...
        [1 3 5 7 9 11 13 15 17],'XTickLabel',...
        {'1','3','5','7','9','11','13','15','17'},'YTickLabel',...
        {'0\%','20\%','40\%','60\%','80\%','100\%'});
   
    legend1 = legend(axes1,'show');
    set(legend1,'Interpreter','latex','FontSize',14);
    title(legend1,'Supply');

end
