%% Analysis: Resource Supply

% import experimental data as "rawdata"

% refine data with parameter ranges
data = rawdata;
%data = rawdata(rawdata.l == 0.8,:);
%data = data(data.Sparsity == 0.2,:);

res_total = struct();

for i = [1 2 3 5 7 10]

    data = rawdata(rawdata.ENV == i,:);
    SK_data = ResistanceAnalysis(data);
    res_total.('E'+string(i)) = SK_data.RES;

end

SKPlot(res_total)


function SK_summary_data = ResistanceAnalysis(data)
    SK_sort = struct();

    SK_summary_data = table('Size',[5 7], ...
        'VariableTypes',{'double','double','double','double','double','double','double'},...
        'VariableNames',{'N',     'LOAD',  'ENV',   'S',     'LOADf', 'RICHf', 'RES'});

    for i = [3 6 9 12 15 18]
        SK_sort.('K'+string(i)) = data(data.SK == i,:);

        SK_summary_data(i/3,:) = {length(SK_sort.('K'+string(i)).COM),...
            sum(SK_sort.('K'+string(i)).LOAD)/length(SK_sort.('K'+string(i)).COM),...
            sum(SK_sort.('K'+string(i)).ENV)/length(SK_sort.('K'+string(i)).COM),...
            sum(SK_sort.('K'+string(i)).S)/length(SK_sort.('K'+string(i)).COM),...
            sum(SK_sort.('K'+string(i)).LOADf)/length(SK_sort.('K'+string(i)).COM),...
            sum(SK_sort.('K'+string(i)).RICHf)/length(SK_sort.('K'+string(i)).COM),...
            sum(SK_sort.('K'+string(i)).OUTCOME == 'RES') / length(SK_sort.('K'+string(i)).COM) };
    end
end

function SKPlot(data_struct)

    %CREATEFIGURE(Y1, Y2, Y3, YMatrix1, Y4)
    %  Y1:  vector of plot y data
    %  Y2:  vector of plot y data
    %  Y3:  vector of plot y data
    %  YMATRIX1:  matrix of plot y data
    %  Y4:  vector of plot y data

    %  Auto-generated by MATLAB on 06-Feb-2025 18:42:31

    % Create figure
    figure;

    % Create axes
    axes1 = axes;
    hold(axes1,'on');

    X = [3 6 9 12 15 18];

    Y1 = data_struct.E1;
    Y2 = data_struct.E2;
    Y3 = data_struct.E3;
    Y4 = data_struct.E5;
    Y5 = data_struct.E7;
    Y6 = data_struct.E10;

    % Create plot
    plot(X,Y1,'DisplayName','1','MarkerSize',20,'Marker','.','LineWidth',2,'Color',[0.30,0.75,0.93],'Marker','.','MarkerSize',30);
    plot(X,Y2,'DisplayName','2','MarkerSize',20,'Marker','.','LineWidth',2,'Color',[0 0.529411764705882 0.890196078431372],'Marker','.','MarkerSize',30);
    plot(X,Y3,'DisplayName','3','MarkerSize',20,'Marker','.','LineWidth',2,'Color',[0 0.458823529411765 0.768627450980392],'Marker','.','MarkerSize',30);
    plot(X,Y4,'DisplayName','5','MarkerSize',20,'Marker','.','LineWidth',2,'Color',[0 0.4 0.670588235294118],'Marker','.','MarkerSize',30);
    plot(X,Y5,'DisplayName','7','MarkerSize',20,'Marker','.','LineWidth',2,'Color',[0 0.341176470588235 0.56078431372549],'Marker','.','MarkerSize',30);
    plot(X,Y6,'DisplayName','10','MarkerSize',20,'Marker','.','LineWidth',2,'Color',[0 0.258823529411765 0.431372549019608],'Marker','.','MarkerSize',30);
    
    % Create ylabel
    ylabel({'Resistance Outcomes'},'FontSize',24,'FontName','EB Garamond');

    % Create xlabel
    xlabel({'Units of Resource Input'},'FontSize',24,...
        'FontName','EB Garamond');

    % Create title
    %title({'Richness-Resistance Curve','by Resource Supply'},'FontSize',30,...
    %    'FontName','EB Garamond');

    xlim(axes1,[3 18]);
    ylim(axes1,[0 1]);

    hold(axes1,'off');
    
    set(axes1,'FontSize',20,'TickLabelInterpreter','latex','XTick',...
        [3 6 9 12 15 18],'XTickLabel',...
        {'3','6','9','12','15','18'},'YTick',[0 0.2 0.4 0.6 0.8 1],'YTickLabel',...
        {'0\%','20\%','40\%','60\%','80\%','100\%'});
   
    legend1 = legend(axes1,'show');
    set(legend1,'Interpreter','latex','FontSize',16,'Location','southwest');
    title(legend1,'Diversity');

end